---
- name: restart Filebeat
  service:
    name: filebeat
    state: restarted
  when: ansible_virtualization_type != 'docker'
- name: start Filebeat
  command:
    cmd: "/usr/share/filebeat/bin/filebeat &"
    creates: /tmp/.filebeat.lock
  when: ansible_virtualization_type == 'docker'
