---
- name: Converge Elasticsearch
  hosts: elastic-instance
  tasks:
    - name: "Include elastic-role"
      include_role:
        name: "elastic"
- name: Converge Kibana
  hosts: kibana-instance
  tasks:
    - name: "Include kibana-role"
      include_role:
        name: "kibana-role"
- name: Converge Filebeat
  hosts: filebeat-instance
  tasks:
    - name: "Include filebeat-role"
      include_role:
        name: "filebeat-role"